name: TrainShop CI Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install API dependencies
        run: npm install
        working-directory: api

      - name: Qualité du code (Lint)
        run: npm run lint
        working-directory: api

      - name: Run API tests
        run: npm test
        working-directory: api

      - name: Build API Docker image
        run: docker build -t trainshop-api ./api

      - name: Build Frontend Docker image
        run: docker build -t trainshop-frontend ./frontend

      - name: Run Container & Healthcheck
        run: |
          docker run -d --name api-check -p 3000:3000 -e SKIP_DB_CHECK=true trainshop-api
          sleep 5
          curl --fail http://localhost:3000/health || exit 1

      - name: Nettoyage du Container
        if: always()
        run: docker rm -f api-check