name: TrainShop Starter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-api:
    name: Tester API
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer dépendances API
        working-directory: api
        run: npm install

      - name: Vérifier la qualité du code
        working-directory: api
        run: npm run lint

      - name: Lancer les tests API
        working-directory: api
        run: npm test

  docker-build:
    name: Vérifier les builds Docker
    runs-on: ubuntu-latest
    needs: test-api

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Build image API
        run: docker build -t trainshop-api ./api

      - name: Build image Frontend
        run: docker build -t trainshop-frontend ./frontend

      - name: Lancer le conteneur API
        run: docker run -d --name trainshop-api -p 3000:3000 trainshop-api

      - name: Attendre le démarrage de l’API
        run: sleep 10

      - name: Afficher les conteneurs Docker
        run: docker ps -a

      - name: Vérifier /health
        run: curl -f http://localhost:3000/health

      - name: Afficher les logs API
        if: always()
        run: docker logs trainshop-api

      - name: Afficher les stats Docker
        if: always()
        run: docker stats --no-stream

      - name: Nettoyer le conteneur
        if: always()
        run: docker rm -f trainshop-api